basePath: /
info:
  contact: {}
  description: Tournament Records and Metrics Assistant
  title: TRAMA API
  version: "1.0"
paths:
  /api/ping:
    get:
      description: Returns ok if the service is reachable
      responses:
        "200":
          description: ok
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
