basePath: /
info:
  contact: {}
  description: Tournament Records and Metrics Assistant
  title: TRAMA API
  version: "1.0"
paths:
  /api/ping:
    get:
      description: Returns ok
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
swagger: "2.0"
